name: ci-workflow
on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install --production

      - run: sudo npm i -g ts-node
      - name: Subscription scope test
        env:
          INPUT_SCOPE: subscription
          INPUT_SUBSCRIPTIONID: ${{ secrets.SUBSCRIPTION_ID }}
          INPUT_REGION: centralus
          INPUT_TEMPLATE: https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/emptyRG.json
          INPUT_PARAMETERS: rgName=demoResourceGroup rgLocation=centralus
          INPUT_DEPLOYMENTNAME: github-test-subs
        run: ts-node test/main.tests.ts
