name: ci-workflow
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        scope:  subscription
        subscriptionId: c00d16c7-6c1f-4c03-9be1-6934a4c49682
        template: examples/template/template.json
        region: WestUS 
        parameters: examples/template/parameters.json
        
    
